version: "3.8"

services:

  # YOLO-API
  api-yolo:
    image: siali/ia-safe:dev_2-58
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3002/check_status"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 40s
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    environment:
      - LOGLEVEL=debug
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./cfgs/:/cfgs/
      - ./files/:/files/
      - ./models/:/models/  # Corrigido 'modees'
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 3002:3002
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3002", "--reload"]



  # BACK 
  main:
    build:
      context: . # Directorio donde se encuentra Dockerfile_main
      dockerfile: Dockerfile # Nombre de tu Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    depends_on:
      - api-yolo
    restart: unless-stopped
    tty: true
    # env_file:
    #   - .env
    environment:
      - API_URL=http://api-yolo:3002
      - LOGLEVEL=debug
      - TZ=Europe/Madrid  # Configura la zona horaria de Madrid

    volumes:
      - ./src/:/src/
      - ./cfgs/:/cfgs/
      - ./files/:/files/
      - ./models/:/models/
      - /etc/localtime:/etc/localtime

    entrypoint: [ "sh", "-c", "sleep 10 && python -u /src/main.py"]
